### ISSUE TITLE
Package @domain-group/fe-brary does not exist on NPM

### ISSUE THREAD

**Issue by rafaellucio** [DomainGroupOSS/sass-to-emotion#3]
Hello guys, 

I try to use this library but identify that doesn't exist one package on NPM `@domain-group/fe-brary`

![Screenshot from 2019-08-08 12-41-47](https://user-images.githubusercontent.com/2213926/62717530-6fba4c00-b9da-11e9-91c3-cff38217bb70.png)

Do you can provide this library to open source?

**Comment by guy-kdm** [comment]
Or maybe just put a little warning at the README.md

Cool project BTW!

**Comment by mattcolman** [comment]
Hi, sorry for the late reply! We're using this package internally at Domain. It works great! But it isn't quite ready to be consumed externally. fe-brary is our internal theme library so we reference that to convert sass variables to emotion variables. Ideally we can separate the two and provide a config to this script where you can define how to map variables. Anyway PRs welcome if you want to remove fe-brary as a dep. Thanks!

**Comment by albertstill** [comment]
Hi @rafaellucio @guy-kdm, sorry for the late response. I've recently made a change to the repo that makes `@domain-group/fe-brary` an optional dependency so users outside of Domain can install and [run](https://github.com/DomainGroupOSS/sass-to-emotion#sass) the transform. Let me know if you have any issues. Cheers
